### PR TITLE
Add cjs and esm support

### PR DESCRIPTION
**Pull request by Nesopie**
Adds: 
- Support for CJS and ESM import
- Replaced `Buffer` with `Uint8Array` to be compatible with browser (and also uses `crypto.getRandomValues`)
- Replaced typeforce with valibot

### CODE REVIEW

**Comment by encloinc** [comment]
https://www.npmjs.com/package/ecpair-esm
went ahead and uploaded to npm @Nesopie since mantainers havent added. Thanks :)

**Comment by encloinc** [comment]
> LGTM [0c8666f](https://github.com/bitcoinjs/ecpair/commit/0c8666fba4b1d626aa5a0ff81f88005ea1dee3b2)
> 
> As mentioned on Matrix, we'll publish this along with all the other major libraries.
> 
> I highly recommend against installing random forks published from random accounts with barely any public history.
> 
> Sure they might be trustworthy members of the community just eager to get their hands on an experimental PR, but they could also be adding a backdoor.
> 
> Be careful out there.

Hey, the commits and the fork were/are public on my GitHub and anyone can verify that there is no malicious intent. there was no need for this :)

**Comment by junderw** [comment]
You did not post a link to your GitHub.

You posted a link to the npmjs package, encouraging blind downloading.

if you had linked the fork, the branch, the commit or diff link on GitHub I wouldn’t need to delete it.

there is nothing preventing GitHub and npmjs from being completely different. Sure you can download the tarball and extract it and verify it that way, but no one does that, and if they’re told to do that it would make better sense to use GitHub for the dependency directly.

> there was no need for this

yes there was. Don’t link random packages or else you will be assumed to be a malicious actor. It’s that simple.

**Comment by encloinc** [comment]
> You did not post a link to your GitHub.
> 
> You posted a link to the npmjs package, encouraging blind downloading.
> 
> if you had linkesd the fork, the branch, the commit or diff link on GitHub I wouldn’t need to delete it.
> 
> there is nothing preventing GitHub and npmjs from being completely different. Sure you can download the tarball and extract it and verify it that way, but no one does that, and if they’re told to do that it would make better sense to use GitHub for the dependency directly.
> 
> > there was no need for this
> 
> yes there was. Don’t link random packages or else you will be assumed to be a malicious actor. It’s that simple.

The package in question has a link to the fork and yeah like you mentioned they can verify the tarball. Infact you couldve done that yourself before accusing me of being malicious :D

Maybe dont make assumptions that have no foundation. I made the package because theres other PRs that havent been reviewed since last year - but hey if making a package got you to accept a much needed merge rather than waiting a year thats a win for me

**Pull request merged**
